sudo: false
language: ruby

branches:
  only:
    - master

gemfile:
  - chef-client-version.gemfile

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.3.1

env:
  CHEF_VERSION=master

script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake build
  - bundle exec rake driver:cycle

notifications:
  email: false
  slack:
    secure: Ueimquh2DjsPZ24PX+yI9a4QzI0rxNInq8xWkIlbhkrhWtdnnZQT4Rk2Bg89gZkHjvp7NZLvHh5hLc39QlYDEycbx3+BdEryEg+33WpdCnShlzQjcMmOvOXBhs6nyOKvIZAjkrcFwfp/4cftk/2dXoE0Za6B3RBOD2yxeHV/nO0=
    on_failure: change
    on_success: change
